name=FaceDetectESP
version=1.0.0
author=DanantST
maintainer=DanantST
sentence=Face detection for ESP boards using onboard camera.
description=This library allows ESP boards with a camera module to perform face detection using machine learning algorithms. It provides an easy-to-use API and high-performance processing capabilities.
category=Computer Vision
url=https://github.com/DanantST/FaceDetectESP
architectures=esp32
includes=FaceDetectESP.h
framework=arduino
platform=espressif:esp32
libraries=ArduinoJson, TFT_eSPI
