#pragma once

#define FACEDETECTESP_VERSION_MAJOR 2
#define FACEDETECTESP_VERSION_MINOR 0
#define FACEDETECTESP_VERSION_PATCH 0

#define FACEDETECTESP_VERSION_STRING "2.0.0"

#define FACEDETECTESP_BUILD_DATE "2026-03-03"
#define FACEDETECTESP_COMPILER_VERSION __cplusplus
